all: \
  $(addsuffix .cht, $(wildcard iso/chart/*.json)) \
  iso/simp/snico.json.cht

iso/chart/%.json.cht: iso/chart/%.json
	tools/funkinchartpak/funkinchartpak $<
iso/simp/sneed.json.cht: iso/simp/sneed.json
	tools/funkinpicopak/funkinpicopak $<
